# Install a role from GitHub
- geerlingguy.jenkins
- geerlingguy.nginx
- geerlingguy.repo-epel
- geerlingguy.git
- geerlingguy.ansible
- geerlingguy.docker
- geerlingguy.pip
- geerlingguy.nodejs
- geerlingguy.awx
- tersmitten.fail2ban
