  - name: Create Allow SSH NSG for {{ vnet.name }}
    azure_rm_securitygroup:
      resource_group: "{{ vnet.resourcegroup }}"
      name: "{{location_prefix}}-{{vnet.env_prefix}}-nsg"
      rules:
        - name: SSH
          source_address_prefix: "{{ ipify_public_ip }}"
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound  
  
  - name: Create virtual network {{ vnet.name }}
    azure_rm_virtualnetwork:
      resource_group: "{{ vnet.resourcegroup }}"
      name: "{{ vnet.name }}"
      address_prefixes: "{{ vnet.range }}"

  - name: Add subnets in {{ vnet.name}}
    azure_rm_subnet:
      resource_group: "{{ vnet.resourcegroup }}"
      name: "{{ item.name }}"
      address_prefix: "{{ item.prefix }}"
      virtual_network: "{{ vnet.name }}"
      security_group_name: "{{location_prefix}}-{{vnet.env_prefix}}-nsg"
    loop: "{{ vnet.subnets }}"
