  - name: Create Mgmt Bastion public IP address
    azure_rm_publicipaddress:
      resource_group: "{{mgmt_resourcegroup}}"
      allocation_method: Dynamic
      name: "{{bastion_node}}-pip"
    register: task_result

  - debug: 
      var: task_result.state.ip_address
      #verbosity: 2

  - name: Create Mgmt Bastion virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{mgmt_resourcegroup}}"
      name: "{{bastion_node}}-nic"
      virtual_network: "{{mgmt_vnet}}"
      subnet: "mgmt_bastion_subnet"
      public_ip_name: "{{bastion_node}}-pip"

  - name: Create Mgmt Bastion VM
    azure_rm_virtualmachine:
      resource_group: "{{mgmt_resourcegroup}}"
      name: "{{bastion_node}}"
      vm_size: "{{ nodesize }}"
      admin_username: "{{admin_user}}"
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: "/home/{{admin_user}}/.ssh/authorized_keys"
          key_data: "{{ssh_key}}"
      network_interfaces: "{{bastion_node}}-nic"
      image:
        offer: "{{ nodeimage.offer}}"
        publisher: "{{ nodeimage.publisher }}"
        sku: "{{ nodeimage.sku }}"
        version: "{{ nodeimage.version }}"

  - name: Create VM Extension
    azure_rm_virtualmachine_extension:
      name: myvmextension
      location: "{{ location }}"
      resource_group: "{{mgmt_resourcegroup}}"
      virtual_machine_name: "{{bastion_node}}"
      publisher: Microsoft.Azure.Extensions
      virtual_machine_extension_type: CustomScript
      type_handler_version: 2.0
      settings: '{"commandToExecute": "touch /tmp/extentiontest "}'
      auto_upgrade_minor_version: true

  - name: add a host to inventory
    add_host:
      hostname: "{{ task_result.state.ip_address }}"
      groups:
        - mgmt
        - bastion