- name: Create Mgmt Resource Group
  azure_rm_resourcegroup:
    name: "{{ mgmt_resourcegroup }}"
    location: "{{ location | default('westeurope') }}"

- name: Create Prod Resource Group
  azure_rm_resourcegroup:
    name: "{{ prod_resourcegroup }}"
    location: "{{ location | default('westeurope') }}"
