  - name: Create Mgmt Bastion public IP address
    azure_rm_publicipaddress:
      resource_group: "{{mgmt_resourcegroup}}"
      allocation_method: Dynamic
      name: "{{bastion_node}}-pip"
    register: task_result

  - debug: 
      var: task_result.state.ip_address

  - name: Create Mgmt Bastion virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{mgmt_resourcegroup}}"
      name: "{{bastion_node}}-nic"
      virtual_network: "{{mgmt_vnet}}"
      subnet: "mgmt_bastion_subnet"
      public_ip_name: "{{bastion_node}}-pip"

  - name: Create Mgmt Bastion VM
    azure_rm_virtualmachine:
      resource_group: "{{mgmt_resourcegroup}}"
      name: "{{bastion_node}}"
      vm_size: Standard_DS1_v2
      admin_username: "{{admin_user}}"
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: "/home/{{admin_user}}/.ssh/authorized_keys"
          key_data: "{{ssh_key}}"
      network_interfaces: "{{bastion_node}}-nic"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest